services:

  # DB (PostgreSQL + pgvector)
  db:
    build:
      context: ./infra/container/db
      dockerfile: Dockerfile
      args:
        DB_PGVECTOR_IMAGE: "${DB_PGVECTOR_IMAGE}"
    # restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 1s
      timeout: 1s
      retries: 30
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_postgres_user
      PGDATA: /var/lib/postgresql/data/pgdata
    secrets:
      - db_postgres_user
      - db_app_tx_user
      - db_app_rag_user
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./infra/container/db/initdb.d:/docker-entrypoint-initdb.d
      - ./data/db/backups/postgres:/var/backups/postgres:ro

secrets:
  db_postgres_user:
    file: ./infra/container/db/secrets/postgres_user.secret
  db_app_tx_user:
    file: ./infra/container/db/secrets/app_tx_user.secret
  db_app_rag_user:
    file: ./infra/container/db/secrets/app_rag_user.secret

volumes:
  db_data:
