---
- name: Ansible 用一時ディレクトリ作成 ※警告対策
  ansible.builtin.file:
    path: "/home/{{ app_user_name }}/.ansible/tmp"
    state: directory
    mode: '0755'
    owner: "{{ app_uid }}"
    group: "{{ app_gid }}"

- name: .env ファイルコピー ※ Windows ホスト側で作成した .env をコンテナ内で利用するためコピー
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../../../.env"
    dest: "/home/{{ app_user_name }}/{{ git_repo_name }}/.env"
    force: no
    mode: '0644'
    owner: "{{ app_uid }}"
    group: "{{ app_gid }}"

- name: クローンリポジトリ内シェルスクリプト検索
  ansible.builtin.find:
    paths: "/home/{{ app_user_name }}/{{ git_repo_name }}"
    patterns: "*.sh"
    recurse: yes
  register: sh_files

- name: クローンリポジトリ内シェルスクリプト実行権限設定 ※ Windows ホスト側でシェルスクリプトコミット時の実行権限消失対応
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: '0755'
  loop: "{{ sh_files.files }}"
  when: sh_files.matched > 0
  loop_control:
    label: "{{ item.path }}"
