---
- name: DB コンテナ用 secrets ディレクトリ作成
  ansible.builtin.file:
    path: "{{ db_secrets_dir }}"
    state: directory
    owner: "{{ app_uid }}"
    group: "{{ app_gid }}"
    mode: '0700' # app_uid を指定してコンテナを起動するため 0700 に設定

- name: DB パスワードファイル作成
  ansible.builtin.copy:
    dest: "{{ db_secrets_dir }}/{{ item.path }}"
    content: "{{- item.value -}}" # Jinja2の {{- ... -}} を使用して前後の空白・改行除去
    owner: "{{ app_uid }}"
    group: "{{ app_gid }}"
    mode: '0600' # app_uid を指定してコンテナを起動するため 0600 に設定
  loop:
    - { path: "postgres_user.secret", value: "{{ db_postgres_user_password }}" }
    - { path: "app_tx_user.secret", value: "{{ db_app_tx_user_password }}" }
    - { path: "app_rag_user.secret", value: "{{ db_app_rag_user_password }}" }
  no_log: true # コンソールパスワード表示防止
